# Generated by Django 3.1.7 on 2021-10-06 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvideos',
            name='like_video',
            field=models.ManyToManyField(blank=True, related_name='like_video', to=settings.AUTH_USER_MODEL),
        ),
    ]
