# Generated by Django 3.1.7 on 2021-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210919_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphotos',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
