# Generated by Django 3.1.7 on 2021-09-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20210919_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphotos',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postphotos',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
