# Generated by Django 3.1.7 on 2021-09-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210918_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
